use std::fs::{create_dir_all, File};
use std::io::Write;
use std::path::PathBuf;

fn get_home() -> Option<PathBuf> {
    std::env::var("HOME").ok().map(PathBuf::from)
}

/// Werkt Kitty styling bij via ~/.config/kitty/zenith-theme.conf
pub fn update_kitty(bg_hex: &str, fg_hex: &str, opacity: f64, font_size: f64) {
    let home = match get_home() {
        Some(h) => h,
        None => return,
    };
    let dir = home.join(".config/kitty");
    let _ = create_dir_all(&dir);

    let bg_clean = bg_hex.trim_start_matches('#');
    let fg_clean = fg_hex.trim_start_matches('#');

    let conf = format!(
        "# Generated by Zenith Control\n\
        background #{}\n\
        foreground #{}\n\
        background_opacity {:.2}\n\
        font_size {:.1}\n",
        bg_clean, fg_clean, opacity, font_size
    );

    if let Ok(mut f) = File::create(dir.join("zenith-theme.conf")) {
        let _ = f.write_all(conf.as_bytes());
    }

    // Vraag Kitty instanties om live te herladen
    let _ = std::process::Command::new("pkill")
        .args(["-SIGUSR1", "kitty"])
        .spawn();
}

/// Werkt Rofi styling bij via ~/.config/rofi/zenith-theme.rasi
pub fn update_rofi(bg_hex: &str, fg_hex: &str, opacity: f64, rounding: i32) {
    let home = match get_home() {
        Some(h) => h,
        None => return,
    };
    let dir = home.join(".config/rofi");
    let _ = create_dir_all(&dir);

    let bg_clean = bg_hex.trim_start_matches('#');
    let fg_clean = fg_hex.trim_start_matches('#');

    let r = u8::from_str_radix(bg_clean.get(0..2).unwrap_or("1e"), 16).unwrap_or(30);
    let g = u8::from_str_radix(bg_clean.get(2..4).unwrap_or("1e"), 16).unwrap_or(30);
    let b = u8::from_str_radix(bg_clean.get(4..6).unwrap_or("2e"), 16).unwrap_or(46);

    let rasi = format!(
        "/* Generated by Zenith Control */\n\
        * {{\n\
            bg-color: rgba({}, {}, {}, {:.2});\n\
            fg-color: #{};\n\
            window-radius: {}px;\n\
        }}\n\
        window {{\n\
            background-color: @bg-color;\n\
            border-radius: @window-radius;\n\
        }}\n\
        element-text {{\n\
            text-color: @fg-color;\n\
        }}\n",
        r, g, b, opacity, fg_clean, rounding
    );

    if let Ok(mut f) = File::create(dir.join("zenith-theme.rasi")) {
        let _ = f.write_all(rasi.as_bytes());
    }
}

/// Werkt Quickshell variabelen bij via ~/.config/quickshell/zenith-theme.json
#[allow(dead_code)]
pub fn update_quickshell(cfg: &crate::backend::config::ZenithConfig) {
    let home = match get_home() {
        Some(h) => h,
        None => return,
    };
    let dir = home.join(".config/quickshell");
    let _ = create_dir_all(&dir);

    let bg_clean = cfg.qs_bg.trim_start_matches('#');
    let acc_clean = cfg.qs_accent.trim_start_matches('#');
    let border_clean = cfg.qs_border_color.trim_start_matches('#');
    let text_clean = cfg.qs_text_color.trim_start_matches('#');
    let pill_bg_clean = cfg.qs_pill_bg.trim_start_matches('#');

    let json = format!(
        "{{\n  \
          \"background\": \"#{}\",\n  \
          \"accent\": \"#{}\",\n  \
          \"opacity\": {:.2},\n  \
          \"height\": {},\n  \
          \"position\": \"{}\",\n  \
          \"rounding\": {},\n  \
          \"margin_h\": {},\n  \
          \"margin_v\": {},\n  \
          \"border_width\": {},\n  \
          \"border_color\": \"#{}\",\n  \
          \"text_color\": \"#{}\",\n  \
          \"font_size\": {},\n  \
          \"floating\": {},\n  \
          \"bar_style\": \"{}\",\n  \
          \"pill_bg\": \"#{}\",\n  \
          \"pill_opacity\": {:.2},\n  \
          \"pill_rounding\": {},\n  \
          \"module_spacing\": {},\n  \
          \"brand_text\": \"{}\",\n  \
          \"show_brand\": {},\n  \
          \"status_text\": \"{}\",\n  \
          \"show_status_badge\": {},\n  \
          \"show_workspaces\": {},\n  \
          \"show_launcher_btn\": {},\n  \
          \"show_cpu\": {},\n  \
          \"show_ram\": {},\n  \
          \"show_battery\": {},\n  \
          \"show_volume\": {},\n  \
          \"show_bluetooth\": {},\n  \
          \"show_network\": {},\n  \
          \"show_media\": {},\n  \
          \"show_clock\": {},\n  \
          \"show_seconds\": {},\n  \
          \"show_power_btn\": {}\n\
        }}\n",
        bg_clean, acc_clean, cfg.qs_opacity, cfg.qs_height, cfg.qs_position,
        cfg.qs_rounding, cfg.qs_margin_h, cfg.qs_margin_v, cfg.qs_border_width,
        border_clean, text_clean, cfg.qs_font_size, cfg.qs_floating,
        cfg.qs_bar_style, pill_bg_clean, cfg.qs_pill_opacity, cfg.qs_pill_rounding,
        cfg.qs_module_spacing, cfg.qs_brand_text, cfg.qs_show_brand,
        cfg.qs_status_text, cfg.qs_show_status_badge,
        cfg.qs_show_workspaces, cfg.qs_show_launcher_btn, cfg.qs_show_cpu, cfg.qs_show_ram,
        cfg.qs_show_battery, cfg.qs_show_volume, cfg.qs_show_bluetooth, cfg.qs_show_network,
        cfg.qs_show_media, cfg.qs_show_clock, cfg.qs_show_seconds, cfg.qs_show_power_btn
    );

    if let Ok(mut f) = File::create(dir.join("zenith-theme.json")) {
        let _ = f.write_all(json.as_bytes());
    }

    // Werkt ook zenith-shell.json bij voor het nieuwe modulaire Quickshell systeem
    let mut shell_cfg = crate::backend::shell_config::ZenithShellConfig::load_or_default();
    shell_cfg.styling.background = format!("#{}", bg_clean);
    shell_cfg.styling.accent = format!("#{}", acc_clean);
    shell_cfg.styling.opacity = cfg.qs_opacity;
    shell_cfg.styling.rounding = cfg.qs_rounding;
    shell_cfg.styling.margin_h = cfg.qs_margin_h;
    shell_cfg.styling.margin_v = cfg.qs_margin_v;
    shell_cfg.styling.border_width = cfg.qs_border_width;
    shell_cfg.styling.border_color = format!("#{}", border_clean);
    shell_cfg.styling.text_color = format!("#{}", text_clean);
    shell_cfg.styling.font_size = cfg.qs_font_size;
    shell_cfg.styling.pill_bg = format!("#{}", pill_bg_clean);
    shell_cfg.styling.pill_opacity = cfg.qs_pill_opacity;
    shell_cfg.styling.pill_rounding = cfg.qs_pill_rounding;
    shell_cfg.styling.module_spacing = cfg.qs_module_spacing;

    shell_cfg.layout.position = cfg.qs_position.clone();
    shell_cfg.layout.height = cfg.qs_height;
    shell_cfg.layout.floating = cfg.qs_floating;
    shell_cfg.layout.bar_style = cfg.qs_bar_style.clone();

    let _ = shell_cfg.save();

    // Werkt ook ~/.config/hypr/scripts/quickshell/qs_colors.json bij indien aanwezig
    let qs_colors_path = home.join(".config/hypr/scripts/quickshell/qs_colors.json");
    if qs_colors_path.exists() {
        if let Ok(content) = std::fs::read_to_string(&qs_colors_path) {
            if let Ok(mut parsed) = serde_json::from_str::<serde_json::Value>(&content) {
                if let Some(obj) = parsed.as_object_mut() {
                    let bg_val = serde_json::Value::String(format!("#{}", bg_clean));
                    let acc_val = serde_json::Value::String(format!("#{}", acc_clean));
                    obj.insert("base".to_string(), bg_val.clone());
                    obj.insert("mantle".to_string(), bg_val.clone());
                    obj.insert("crust".to_string(), bg_val.clone());
                    obj.insert("surface0".to_string(), bg_val);
                    obj.insert("blue".to_string(), acc_val.clone());
                    obj.insert("sapphire".to_string(), acc_val.clone());
                    obj.insert("mauve".to_string(), acc_val);
                    if let Ok(new_json) = serde_json::to_string_pretty(&parsed) {
                        let _ = std::fs::write(&qs_colors_path, new_json);
                    }
                }
            }
        }
        // Forceer reload op custom Quickshell indien draaiend
        let shell_qml = home.join(".config/hypr/scripts/quickshell/Shell.qml");
        let _ = std::process::Command::new("qs")
            .args(["-p", &shell_qml.to_string_lossy(), "ipc", "call", "topbar", "forceReload"])
            .spawn();
    }

    // Signaleer Quickshell om het themabestand opnieuw te laden
    let _ = std::process::Command::new("pkill")
        .args(["-SIGUSR1", "quickshell"])
        .spawn();
}

/// Slaat ZenithShellConfig direct op en synchroniseert ook het legacy zenith-theme.json
pub fn sync_shell_config(shell_cfg: &crate::backend::shell_config::ZenithShellConfig) {
    let _ = shell_cfg.save();

    let home = match get_home() {
        Some(h) => h,
        None => return,
    };
    let dir = home.join(".config/quickshell");
    let _ = create_dir_all(&dir);

    let bg_clean = shell_cfg.styling.background.trim_start_matches('#');
    let acc_clean = shell_cfg.styling.accent.trim_start_matches('#');
    let border_clean = shell_cfg.styling.border_color.trim_start_matches('#');
    let text_clean = shell_cfg.styling.text_color.trim_start_matches('#');
    let pill_bg_clean = shell_cfg.styling.pill_bg.trim_start_matches('#');

    let json = format!(
        "{{\n  \
          \"background\": \"#{}\",\n  \
          \"accent\": \"#{}\",\n  \
          \"opacity\": {:.2},\n  \
          \"height\": {},\n  \
          \"position\": \"{}\",\n  \
          \"rounding\": {},\n  \
          \"margin_h\": {},\n  \
          \"margin_v\": {},\n  \
          \"border_width\": {},\n  \
          \"border_color\": \"#{}\",\n  \
          \"text_color\": \"#{}\",\n  \
          \"font_size\": {},\n  \
          \"floating\": {},\n  \
          \"bar_style\": \"{}\",\n  \
          \"pill_bg\": \"#{}\",\n  \
          \"pill_opacity\": {:.2},\n  \
          \"pill_rounding\": {},\n  \
          \"module_spacing\": {}\n\
        }}\n",
        bg_clean, acc_clean, shell_cfg.styling.opacity, shell_cfg.layout.height, shell_cfg.layout.position,
        shell_cfg.styling.rounding, shell_cfg.styling.margin_h, shell_cfg.styling.margin_v, shell_cfg.styling.border_width,
        border_clean, text_clean, shell_cfg.styling.font_size, shell_cfg.layout.floating,
        shell_cfg.layout.bar_style, pill_bg_clean, shell_cfg.styling.pill_opacity, shell_cfg.styling.pill_rounding,
        shell_cfg.styling.module_spacing
    );

    if let Ok(mut f) = File::create(dir.join("zenith-theme.json")) {
        let _ = f.write_all(json.as_bytes());
    }

    let _ = std::process::Command::new("pkill")
        .args(["-SIGUSR1", "quickshell"])
        .spawn();
}