use std::fs::{create_dir_all, read_to_string, File};
use std::io::Write;
use std::path::PathBuf;
use std::process::Command;

fn get_waybar_dir() -> Option<PathBuf> {
    let home = std::env::var("HOME").ok()?;
    Some(PathBuf::from(home).join(".config/waybar"))
}

pub fn reload_waybar() {
    let _ = Command::new("pkill")
        .args(["-SIGUSR2", "waybar"])
        .spawn();
}

/// Werkt position ("top" of "bottom") en height bij in ~/.config/waybar/config
pub fn update_config(position: &str, height: i32) {
    let dir = match get_waybar_dir() {
        Some(d) => d,
        None => return,
    };
    let config_path = dir.join("config");

    if let Ok(raw) = read_to_string(&config_path) {
        // Strip eventuele comments zodat serde_json het betrouwbaar leest
        let cleaned: String = raw
            .lines()
            .filter(|l| !l.trim().starts_with("//"))
            .collect::<Vec<&str>>()
            .join("\n");

        if let Ok(mut val) = serde_json::from_str::<serde_json::Value>(&cleaned) {
            if let Some(obj) = val.as_object_mut() {
                obj.insert("position".to_string(), serde_json::Value::String(position.to_string()));
                obj.insert("height".to_string(), serde_json::Value::Number(height.into()));

                if let Ok(serialized) = serde_json::to_string_pretty(&val) {
                    if let Ok(mut f) = File::create(&config_path) {
                        let _ = f.write_all(serialized.as_bytes());
                    }
                }
            }
        }
    }

    reload_waybar();
}

/// Schrijft custom CSS override weg naar ~/.config/waybar/zenith-style.css
pub fn update_style(bg_hex: &str, opacity: f64, rounding: i32) {
    let dir = match get_waybar_dir() {
        Some(d) => d,
        None => return,
    };
    let _ = create_dir_all(&dir);

    let style_path = dir.join("zenith-style.css");
    if let Ok(mut f) = File::create(style_path) {
        // Zet hex om naar rgba voor css
        let r = u8::from_str_radix(bg_hex.get(0..2).unwrap_or("1e"), 16).unwrap_or(30);
        let g = u8::from_str_radix(bg_hex.get(2..4).unwrap_or("1e"), 16).unwrap_or(30);
        let b = u8::from_str_radix(bg_hex.get(4..6).unwrap_or("2e"), 16).unwrap_or(46);

        let css = format!(
            "/* Generated by Zenith Control */\n\
            window#waybar {{\n\
                background-color: rgba({}, {}, {}, {:.2});\n\
                border-radius: {}px;\n\
            }}\n",
            r, g, b, opacity, rounding
        );

        let _ = f.write_all(css.as_bytes());
    }

    reload_waybar();
}